# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HQblkdiag <- function(C, cnt) {
    .Call(`_BPST_HQblkdiag`, C, cnt)
}

HQbary <- function(V, Tr, xx, yy) {
    .Call(`_BPST_HQbary`, V, Tr, xx, yy)
}

HQgetInd <- function(V, Tr, xx, yy) {
    .Call(`_BPST_HQgetInd`, V, Tr, xx, yy)
}

mtxrbind <- function(a, b) {
    .Call(`_BPST_mtxrbind`, a, b)
}

mtxcbind <- function(a, b) {
    .Call(`_BPST_mtxcbind`, a, b)
}

vbind <- function(a, b) {
    .Call(`_BPST_vbind`, a, b)
}

BSpline2 <- function(V, Tr, d, r, xx, yy) {
    .Call(`_BPST_BSpline2`, V, Tr, d, r, xx, yy)
}

BSpline <- function(V, Tr, d, r, xx, yy) {
    .Call(`_BPST_BSpline`, V, Tr, d, r, xx, yy)
}

CrIndices <- function(d, r) {
    .Call(`_BPST_CrIndices`, d, r)
}

CrCellArrays <- function(d, r) {
    .Call(`_BPST_CrCellArrays`, d, r)
}

CrArrays <- function(d, r) {
    .Call(`_BPST_CrArrays`, d, r)
}

degree <- function(m) {
    .Call(`_BPST_degree`, m)
}

indices <- function(d) {
    .Call(`_BPST_indices`, d)
}

bary <- function(V1, V2, V3, X, Y) {
    .Call(`_BPST_bary`, V1, V2, V3, X, Y)
}

tcord <- function(V1, V2, V3, u) {
    .Call(`_BPST_tcord`, V1, V2, V3, u)
}

triarea <- function(V1, V2, V3) {
    .Call(`_BPST_triarea`, V1, V2, V3)
}

locate <- function(I1, J1, K1, I, J, K) {
    .Call(`_BPST_locate`, I1, J1, K1, I, J, K)
}

dirder <- function(Bin, lam1, lam2, lam3) {
    .Call(`_BPST_dirder`, Bin, lam1, lam2, lam3)
}

build <- function(d) {
    .Call(`_BPST_build`, d)
}

locEng <- function(V1, V2, V3, Mat, d) {
    .Call(`_BPST_locEng`, V1, V2, V3, Mat, d)
}

energy <- function(V, Tr, d) {
    .Call(`_BPST_energy`, V, Tr, d)
}

insideVT <- function(V, Tr, xx, yy) {
    .Call(`_BPST_insideVT`, V, Tr, xx, yy)
}

mvrbind <- function(a, b) {
    .Call(`_BPST_mvrbind`, a, b)
}

mvcbind <- function(a, b) {
    .Call(`_BPST_mvcbind`, a, b)
}

newcol <- function(B0, c0) {
    .Call(`_BPST_newcol`, B0, c0)
}

tdata <- function(V, Tr) {
    .Call(`_BPST_tdata`, V, Tr)
}

